apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - binder.yaml
  - dispatcher.yaml
  - scheduler-0.yaml
  - scheduler-1.yaml
  - scheduler-2.yaml
  - binder-config-demo.yaml
  - scheduler-config-demo.yaml
  - controller-manager.yaml
